//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torque.Compiler.Diagnostics.Catalogs.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TypeCheckerDiagnostics {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypeCheckerDiagnostics() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Torque.Compiler.Diagnostics.Catalogs.Resources.TypeCheckerDiagnostics", typeof(TypeCheckerDiagnostics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string TypeDiffers {
            get {
                return ResourceManager.GetString("TypeDiffers", resourceCulture);
            }
        }

        internal static string PointerExpected {
            get {
                return ResourceManager.GetString("PointerExpected", resourceCulture);
            }
        }

        internal static string CannotUseVoidHere {
            get {
                return ResourceManager.GetString("CannotUseVoidHere", resourceCulture);
            }
        }

        internal static string ExpressionDoesNotReturnAnyValue {
            get {
                return ResourceManager.GetString("ExpressionDoesNotReturnAnyValue", resourceCulture);
            }
        }

        internal static string CannotCallNonFunction {
            get {
                return ResourceManager.GetString("CannotCallNonFunction", resourceCulture);
            }
        }

        internal static string ArityDiffers {
            get {
                return ResourceManager.GetString("ArityDiffers", resourceCulture);
            }
        }

        internal static string CannotUseLetHere {
            get {
                return ResourceManager.GetString("CannotUseLetHere", resourceCulture);
            }
        }

        internal static string CannotHaveAZeroSizedArray {
            get {
                return ResourceManager.GetString("CannotHaveAZeroSizedArray", resourceCulture);
            }
        }

        internal static string ExpectedAReturnValue {
            get {
                return ResourceManager.GetString("ExpectedAReturnValue", resourceCulture);
            }
        }
    }
}
